services:
  api:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/postgres
    depends_on:
      - db
    command: npm run dev

  db:
    image: postgis/postgis:16-master
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data:
